dictionary:
  a: 'ζ'
  b: 'δ'
  c: 'γ'
  d: 'α'
  e: 'Γ'
  f: 'ξ'
  g: 'Ω'
  h: 'Ψ'
  i: 'Χ'
  j: 'Φ'
  k: '∔'
  l: '∂'
  m: '∨'
  n: '⌲'
  o: '⌜'
  p: '⊠'
  q: '│'
  r: '╸'
  s: '⑀'
  t: '╳'
  u: '〆'
  v: '⑇'
  w: '︵'
  x: '︶'
  y: '⑆'
  z: '☲'
nums:
  1: '◔'
  2: '☐'
  3: '⍢'
  4: '⍨'
  5: 'Ѷ'
  6: 'Ӫ'
  7: 'Σ'
  8: '˜'
  9: '*'
  0: '⊝'